### ISSUE TITLE
1

### ISSUE THREAD

**Issue by af913337456** [jwping/wxbot#1]
你好作者，有 qq 版本的吗

**Comment by jwping** [comment]
抱歉，目前没有qq版本

**Comment by af913337456** [comment]
> 抱歉，目前没有qq版本

可以定制开发？ tg：@gavin19877

**Comment by jwping** [comment]
> > 抱歉，目前没有qq版本
> 
> @jwping 可以定制开发？ tg：@gavin19877

我了解的QQ的机器人框架应该很多呀？（酷Q，还有其它github上开源的很多python的框架） 而且这个项目本身也是因为自己在学习使用，而QQ的话我自己没有什么场景会用到，所以没有很多时间去尝试QQ版本抱歉~
